
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Es.Udc.DotNet.PracticaMaD.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ImageUpload
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ImageUpload()
    {

        this.Comment = new HashSet<Comment>();

        this.Tag = new HashSet<Tag>();

        this.UserProfile1 = new HashSet<UserProfile>();

    }


    public long imgId { get; set; }

    public byte[] uploadedImage { get; set; }

    public long usrId { get; set; }

    public long likes { get; set; }

    public string title { get; set; }

    public string descriptions { get; set; }

    public System.DateTime uploadDate { get; set; }

    public Nullable<double> f { get; set; }

    public Nullable<double> t { get; set; }

    public string iso { get; set; }

    public string wb { get; set; }

    public Nullable<long> categoryId { get; set; }



    public virtual Category Category { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Comment> Comment { get; set; }

    public virtual UserProfile UserProfile { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tag> Tag { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserProfile> UserProfile1 { get; set; }

}

}
